services:
  springboot-app:
    build:
      context: ./springboot-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    volumes:
      # - ./springboot-app:/app
      - /app/target
      #- shared-data:/mnt/nfs  # Montando o volume compartilhado NFS
    environment:
      - SPRING_PROFILES_ACTIVE=development
    networks:
      - lumos-network
    restart: always

  go-server:
    build: ./golang-services
    container_name: go-server
    ports:
      - "8081:8081"
    volumes:
      - ./golang-services:/app 
      - shared-data:/mnt/nfs  # Montando volume compartilhado para dados
    environment:
      - ENVIRONMENT=development
    networks:
      - lumos-network
    restart: always

  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs-server
    volumes:
      - shared-data:/srv/nfs/exports  # Usando o volume compartilhado
    environment:
      - SHARED_DIRECTORY=/srv/nfs/exports
    networks:
      - lumos-network
    restart: always

networks:
  lumos-network:
    driver: bridge

volumes:
  shared-data:
