// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ContratoAditivoQuantitativo struct {
	ValorAditivoQuantitativo      sql.NullString
	ContractIDContract            sql.NullInt64
	IDContratoAditivoQuantitativo int64
}

type ContratoAditivoValor struct {
	ValorAditivo           sql.NullString
	ContractIDContract     sql.NullInt64
	IDContratoAditivoValor int64
}

type ContratoEquipe struct {
	IDEquipe int32
}

type ContratoTarefa struct {
	EquipeIDEquipe      sql.NullInt32
	QuantidadeExecutada int32
	QuantidadeRecebida  int32
	ContractIDContract  sql.NullInt64
	IDTarefa            int64
}

type TbCompany struct {
	IDCompany   int64
	CompanyName string
}

type TbContract struct {
	ContractValue  sql.NullString
	CreationDate   sql.NullTime
	IDContract     int64
	City           sql.NullString
	ContractDoc    sql.NullString
	ContractNumber sql.NullString
	Uf             sql.NullString
}

type TbDeposit struct {
	CompanyID   int64
	IDDeposit   int64
	DepositName string
}

type TbGroup struct {
	IDGroup   int64
	GroupName string
}

type TbItem struct {
	IDItem         int32
	ItemQuantity   int32
	ItemTotalValue sql.NullString
	ItemValue      sql.NullString
	IDContract     sql.NullInt64
	IDMaterial     sql.NullInt64
}

type TbLog struct {
	CreationTimestamp sql.NullTime
	IDLog             int64
	IDUser            uuid.NullUUID
	Category          sql.NullString
	Message           sql.NullString
	Type              sql.NullString
}

type TbMaterial struct {
	CostPrice      sql.NullString
	Inactive       bool
	StockAvailable int32
	StockQuantity  int32
	IDCompany      int64
	IDDeposit      int64
	IDMaterial     int64
	IDMaterialType int64
	BuyUnit        string
	MaterialAmps   sql.NullString
	MaterialBrand  sql.NullString
	MaterialLength sql.NullString
	MaterialName   string
	MaterialPower  sql.NullString
	RequestUnit    string
}

type TbMaterialReservation struct {
	QuantityCompleted           int32
	ReservedQuantity            int32
	IDMaterialReservation       int64
	MaterialIDMaterial          sql.NullInt64
	PreMeasurementIDMeasurement sql.NullInt64
	Status                      sql.NullString
	StockReservationName        sql.NullString
}

type TbPreMeasurement struct {
	IDMeasurement int64
	City          sql.NullString
}

type TbRefreshToken struct {
	Revoked    bool
	ExpiryDate time.Time
	IDToken    int64
	IDUser     uuid.UUID
	Token      string
}

type TbRole struct {
	IDRole   int64
	NomeRole sql.NullString
}

type TbStockMovement struct {
	InputQuantity            int32
	PricePerItem             string
	QuantityPackage          int32
	MaterialID               int64
	StockMovementID          int64
	StockMovementRefresh     time.Time
	SupplierID               sql.NullInt64
	UserCreatedIDUser        uuid.NullUUID
	UserFinishedIDUser       uuid.NullUUID
	BuyUnit                  string
	Status                   sql.NullString
	StockMovementDescription sql.NullString
}

type TbStreet struct {
	IDStreet int64
	Name     sql.NullString
}

type TbSupplier struct {
	SupplierID      int64
	SupplierAddress sql.NullString
	SupplierCnpj    sql.NullString
	SupplierContact sql.NullString
	SupplierEmail   sql.NullString
	SupplierName    sql.NullString
	SupplierPhone   sql.NullString
}

type TbTeam struct {
	IDTeam   int64
	Region   sql.NullString
	TeamName sql.NullString
}

type TbTeamMeasurement struct {
	IDMeasurement int64
	IDTeam        int64
}

type TbType struct {
	IDGroup  int64
	IDType   int64
	TypeName string
}

type TbUser struct {
	DateOfBirth sql.NullTime
	IDUser      uuid.UUID
	Email       sql.NullString
	LastName    sql.NullString
	Name        sql.NullString
	Password    sql.NullString
	Username    sql.NullString
}

type TbUsersRole struct {
	IDRole int64
	IDUser uuid.UUID
}
